language: node_js
os:
  - linux
dist: bionic
node_js:
  - 14
addons:
  apt:
    update: true
  chrome: stable
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get -y install python
  - npm update
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run travis
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
