language: node_js
os:
  - linux
node_js:
  - 'lts/*'
services:
  - xvfb
branches:
  only:
    - main
install:
  - npm set progress=false
  - npm install
before_script:
  - export DISPLAY=:99.0
script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run e2e ; fi
