language: node_js
os:
  - linux
dist: bionic
node_js:
  - 12
addons:
  apt:
    update: true
services:
  - xvfb
branches:
  only:
    - main
install:
  - npm install
  - npm install -D jasmine
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export DISPLAY=:99.0
script:
  - npm run travis1 && npm test
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
