language: node_js
os:
  - linux
dist: bionic
node_js:
  - 12
addons:
  apt:
    update: true
services:
  - xvfb
branches:
  only:
    - main
cache:
  directories:
    - node_modules
before_install:
  - npm update
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
  - npm install
  - npm install -D jasmine
before_script:
  - sleep 3 # give xvfb some time to start
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run travis1 && xvfb-run --server-args="-screen 0 1024x768x24" npm run travis2
after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT
